  postgres: 
    image: postgres:14-alpine3.15
    ports: ["5432:5432"]
    restart: always
    networks: [backing-services] 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres